# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf
  - htmlzip

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt

# Settings for more control over Server side search.
# https://docs.readthedocs.io/en/stable/config-file/v2.html#search
search:
  # Define which files pop up higher in the search results
  ranking:
    'docs/source/': 3
    'ema_workbench/**': 2
    'ema_workbench/examples/*': 1
    '**/models/*': -1

  # Exclude some files from the search
  ignore: ['MANIFEST.in', '.gitattributes', '**/.gitignore', '**/data/*', '.eggs/**']
