blank_issues_enabled: true
contact_links:
  - name: Ask a Question or Seek Help
    url: https://github.com/quaquel/EMAworkbench/discussions
    about: "For questions or if you have an issue that you're not sure is caused by the EMAworkbench, please use our Discussions section."
